### ISSUE TITLE
pub run build_runner build doesn't generate code as expected

### ISSUE THREAD

**Issue by weikano** [jorgecoca/todo_reporter.dart#1]
cannot generate .g.dart file when running command.
after adding those codes in example/lib, it works

```dart
// example/lib/todo.dart
part 'todo.g.dart';

// example/lib/second_todo.dart
part 'second_todo.g.dart';
```

**Comment by jorgecoca** [comment]
Sorry, I don't understand what's the issue that you are having. Can you provide me more details? Thanks!

**Comment by weikano** [comment]
You have to add 
```dart
part "todo.g.dart";
```
in example/lib/todo.dart.
Otherwise build_runner won't generate code as expected.

**Comment by jorgecoca** [comment]
I don't know what you are checking, but the example project already has the `*.g.dart` files. For example: https://github.com/jorgecoca/todo_reporter.dart/blob/master/example/lib/todo.g.dart

Closing this issue.

**Comment by weikano** [comment]
Those *.g.dart files were generated by source_gen when you run the pub run build_runner command, right?
So I delete *.g.dart files and try to regenerate those files using pub run under example folder, but nothing happened.
Because you did not add those code in todo.dart
```dart
part 'todo.g.dart'
```
